
# Data Structure & Storage {#sec-energy-intro}

## Introduction

This documents defines how data are obtained, structured and pre-processed.

## Data Structure

### Variables

The following meteorological variables are assessed:

-   Precipitation (Rain)
-   Temperature (minimum and maximum)
-   Global Solar Radiation (GHI)

### Time Resolutions

Even though we are ultimately interested in daily aggregation values (totals or averages), for quality verification purposes, we need higher resolutions. Especially to understand the Markov process and aggreggation, we take the following resolutions: - 15 min Resolution - 1h Resolution - 1 Day Resolution

### Ground Truth Data

For verification purposes, we acquire a series of ground truth data from different weather stations we have access to. The ground truth locations define our geographic points of interest and will be given a loc_id.

Where do we obtain the ground truth:

-   Official Weather Stations through the Meteomatics API (all variables)
-   Rain data from https://www.bodenmessnetz.ch/ in Switzerland (manually extracted)

### Model Data

We further acquire multiple modelled data for each loc_id. We will organize them according to:

-   vendor
-   model

### Storage format

We will store the data in a .rds format. This is a fast, efficient, and lightweight binary columnar storage format designed for efficient storge in the R environment. It enables rapid read and write operations, making it ideal for large datasets.

### Organization of Data

The data will be organized inside the Github Repo as in the following structure:

```         
data/
├── meta_data.feather
│   ├── loc_id
│   ├── ...
│   └── geom
├── rain/
│   ├── loc_1.feather
│   │   ├── res_1d
│   │   │   ├── station(df)
│   │   │   │   ├── timestamp
│   │   │   │   └── value
│   │   │   ├── vendor_A_model_1(df)
│   │   │   │   ├── timestamp
│   │   │   │   └── value
│   │   │   ├── vendor_A_model_2(df)
│   │   │   │   ├── timestamp
│   │   │   │   └── value
│   │   │   ├── vendor_B_model_1(df)
│   │   │   │   ├── timestamp
│   │   │   │   └── value
│   │   │   ├── ...
│   │   │
│   │   ├── res_1h
│   │   │   ├── ...
│   │   │  ...
│   │   │   └──  ...
│   │
│   ├── loc_n.feather
│   │   ├── ...
│   │  ...
│   │   └──  ...
│   ├── ...
├── max_temperature/
│   ├── ...^
├── .../
```

## ...
